# Generated by Django 5.0.6 on 2024-06-11 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kartapp', '0002_alter_product_name_cart'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
